# Generated by Django 5.1.1 on 2024-09-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_sellreciept_total_alter_items_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'permissions': [('manage_items', 'Can manage items')]},
        ),
        migrations.AlterModelOptions(
            name='purchasereciept',
            options={'permissions': [('manage_purchase_receipts', 'Can manage purchase receipts')]},
        ),
        migrations.AlterModelOptions(
            name='sellreciept',
            options={'permissions': [('manage_sell_receipts', 'Can manage sell receipts')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Can manage users')]},
        ),
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
