# Generated by Django 5.1.1 on 2024-09-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_items_options_alter_purchasereciept_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereciept',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sellreciept',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasereciept',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sellreciept',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='purchaseReciept',
        ),
        migrations.DeleteModel(
            name='sellReciept',
        ),
    ]
