import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Manrope } from "next/font/google";
import {Lexend } from "next/font/google";
import{League_Spartan} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const manrope = Manrope({ subsets: ["latin"] });
export const lexend = Lexend({ subsets: ["latin"] });
export const leagueSpartan = League_Spartan({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
